// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    Content: typeof import('./src/components/Content/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Image: typeof import('./src/components/Image/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/index.vue')['default']
    List: typeof import('./src/components/List/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Popover: typeof import('./src/components/Popover/index.vue')['default']
    Preview: typeof import('./src/components/Preview/index.vue')['default']
    PreviewHtml: typeof import('./src/components/PreviewHtml/index.vue')['default']
    Rotation: typeof import('./src/components/Rotation/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectUser: typeof import('./src/components/SelectUser/index.vue')['default']
    Toc: typeof import('./src/components/Toc/index.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu/index.vue')['default']
    ToTopIcon: typeof import('./src/components/ToTopIcon/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
